### ISSUE TITLE
你好，之前我写的vue和ng2，刚接触nerv，想问一下我用了athena2初始化项目，然后我想引入antd，但是会抱react和react-dom的错，请问这里nerv怎么处理

### ISSUE THREAD

**Issue by woshixiaoqianbi** [o2team/athena2#2]

**Comment by luckyadam** [comment]
Hello，在项目的根目录下 `config` 的 `index.js` 配置里可以加入webpack的配置，将`react`、`react-dom` alias 成 `nerv` 如
```
// config/index.js
const config = {
  ...
  webpack: {
    resolve: {
      alias: {
        react: 'nervjs',
        'react-dom': 'nervjs'
      }
    }
  }
}
...
```
可以参考一下项目 [https://github.com/NervJS/nerv-website](https://github.com/NervJS/nerv-website) 的配置

**Comment by woshixiaoqianbi** [comment]
@luckyadam  ok，多谢

**Comment by luckyadam** [comment]
@woshixiaoqianbi 看了一下antd的文档，样式是需要自己引入的，可以在页面的js里引入
```javascript
import 'antd/dist/antd.css'
```

另外，antd的依赖的很多组件使用了 `create-react-class` 来创建组件，Nerv提供了 `nerv-create-class` 来达到同样目的，你需要安装 `nerv-create-class` 包，并且在 `config/index.js` 中增加一条webpack的alias配置

```javascript
// config/index.js
const config = {
  ...
  webpack: {
    resolve: {
      alias: {
        react: 'nervjs',
        'react-dom': 'nervjs',
        'create-react-class': 'nerv-create-class'
      }
    }
  }
}
...
```

**Comment by woshixiaoqianbi** [comment]
@luckyadam 非常感谢

**Comment by vincentmrlau** [comment]
偶然逛到这个issue，@luckyadam 应该使用`babel-plugin-import`这个插件动态引入
